import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { BsSearch } from "react-icons/bs";
import { useState } from "react";
import Weather from "../components/Weather";
import Spinner from '../components/Spinner';

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      // console.log(response.data);
    });
    setCity("");
    setLoading(false);
  };

  if(loading){
    return <Spinner/>
  }else{

    return (
      <div>
        <Head>
          <title>Weather - Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        {/* overlay  */}
        <div className="absolute top-0 right-0 left-0 bottom-0 bg-black/40 z-[1]" />
  
        {/* background image */}
        <Image
          src="https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8d2VhdGhlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60"
          layout="fill"
          className="object-cover"
        />
  
        {/* search bar */}
        <div className="relative  flex justify-between items-center w-full m-auto pt-4 max-w-[500px] text-white z-10">
          <form onSubmit={fetchWeather} className="flex justify-between items-center w-full m-auto bg-transparent p-3 border border-gray-300 text-white rounded-2xl">
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                className="w-full border-none  bg-transparent focus:outline-none text-2xl  "
                type="text"
                placeholder="Search City"
              />
            </div>
            <button className="" onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>
  
        {/* weather data */}
  
        {weather.main && <Weather data={weather}/>}
      </div>
    );
  }

  
}
